name: "DEV DEPLOY"

on:
  push:
    branches:
      - develop

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    uses: ./.github/workflows/terraform.yaml
    with:
      environment: dev
      aws-assume-role-arn: "arn:aws:iam::437491186055:role/github-actions-sts-assumeRole"
      aws-region: "sa-east-1"
      aws-statefile-s3-bucket: "clevisson-sa-east-1-terraform-statefile"
      aws-lock-dynamodb-table: "clevisson-sa-east-1-terraform-lock"